force-app/main/default/objects/Credit_Note__c/Credit_Note__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Note__c/fields/Amount_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Amount_Allocated__c</fullName>
    <label>Amount Allocated</label>
    <summarizedField>Credit_Note_Assignment__c.Amount_Allocated__c</summarizedField>
    <summaryForeignKey>Credit_Note_Assignment__c.Credit_Note__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Credit_Note__c/fields/Amount_Available__c.field-meta.xml
<CustomField>
    <fullName>Amount_Available__c</fullName>
    <formula>Credit_Amount__c - Amount_Allocated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Available</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Note__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Debited</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>Credit_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Note__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partial</fullName>
                <default>true</default>
                <label>Partial</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Note_Assignment__c/Credit_Note_Assignment__c.object-meta.xml
<CustomObject>
    <label>Credit Note Assignment</label>
    <nameField>
        <displayFormat>CNA-{000}</displayFormat>
        <label>Credit Note Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Note Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Note_Assignment__c/fields/Amount_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Amount_Allocated__c</fullName>
    <label>Amount Allocated</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Note_Assignment__c/fields/Credit_Note__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note__c</fullName>
    <label>Credit Note</label>
    <referenceTo>Credit_Note__c</referenceTo>
    <relationshipLabel>Credit Note Assignments</relationshipLabel>
    <relationshipName>Credit_Note_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credit_Note_Assignment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Note Assignments</relationshipLabel>
    <relationshipName>Credit_Note_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <formula>Total_Amount__c - Credit_Note_Credits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Credit_Note_Credits__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Credits__c</fullName>
    <label>Credit Note Credits</label>
    <summarizedField>Credit_Note_Assignment__c.Amount_Allocated__c</summarizedField>
    <summaryForeignKey>Credit_Note_Assignment__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoiceService.cls
public with sharing class InvoiceService {
    @AuraEnabled(cacheable=true)
    public static list<Credit_Note__c> getCreditNotes(Id invId) {
        list<Invoice__c> inv = [SELECT id,Customer__c FROM Invoice__c WHERE id=:invId];
        if(inv!=null && inv.size()>0){
            list<Credit_Note__c> CN = [SELECT id,Name,CreatedDate,Amount_Available__c FROM Credit_Note__c WHERE Invoice__r.Customer__c = :inv[0].Customer__c AND Status__c != 'Closed'];
            return CN;
        }else{
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static Invoice__c getInvoice(Id invId) {
        list<Invoice__c> inv = [SELECT id,Name,CreatedDate,Credit_Note_Credits__c,Total_Amount__c,Amount_Due__c FROM Invoice__c WHERE Id = :invId];
        if(inv!=null && inv.size()>0){
            return inv[0];
        }else{
            return null;
        }
    }
    @AuraEnabled
    public static void saveCreditLines(list<invoiceWrapper> wrp, string InvoiceId) {
        List<id> credIds = new list<id>();
        list<Credit_Note_Assignment__c> noteAssignMent = new list<Credit_Note_Assignment__c>();
        for(invoiceWrapper wr: wrp) {
            if(wr.Amount_To_Credit!=null && wr.Amount_To_Credit!=0) {
                Credit_Note_Assignment__c CNA = new Credit_Note_Assignment__c();
                CNA.Invoice__c = InvoiceId;
                CNA.Amount_Allocated__c = wr.Amount_To_Credit;
                CNA.Credit_Note__c = wr.CredId;
                credIds.add(wr.CredId);
                noteAssignMent.add(CNA);
            }
        }
        try {
            INSERT noteAssignMent;
        }catch(exception e){
            system.debug(e);
        }
        
        Invoice__c inv = [SELECT id,Name,CreatedDate,Credit_Note_Credits__c,Total_Amount__c,Status__c FROM Invoice__c WHERE Id = :InvoiceId];
        if(inv.Total_Amount__c == inv.Credit_Note_Credits__c) {
            inv.Status__c = 'Paid';
        }else if(inv.Total_Amount__c > inv.Credit_Note_Credits__c) {
            inv.Status__c = 'Partially Paid';
        }else if( inv.Credit_Note_Credits__c ==0) {
            inv.Status__c = 'Unpaid';
        }
        try {
            UPDATE inv;
        }catch(exception e){
            system.debug(e);
        }
        list<Credit_Note__c> crNotes = new list<Credit_Note__c>();
        for(Credit_Note__c cNote : [SELECT id,Amount_Available__c FROM Credit_Note__c WHERE id IN :credIds]) {
            if(cNote.Amount_Available__c==0) {
                cNote.Status__c = 'Closed';
            }else if(cNote.Amount_Available__c>0) {
                cNote.Status__c = 'Partial';
            }
            crNotes.add(cNote);
        }
        try {
            UPDATE crNotes;
        }catch(exception e){
            system.debug(e);
        }
    }

    public class invoiceWrapper {
        @AuraEnabled public string CredId{get;set;}
        @AuraEnabled public Date CreatedDate{get;set;}
        @AuraEnabled public Decimal Amount_Available{get;set;}
        @AuraEnabled public Decimal Amount_To_Credit{get;set;}
        @AuraEnabled public string Name{get;set;}
    }
}